services:
  nextjs:
        build: .
        container_name: nextjs-portfolio
        ports:
          - '3000:3000'
        volumes:
          - ./:/app
          - /app/node_modules
        env_file:
          - .env
        