name: Release 
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
    release:
        runs-on: ubuntu-20.04
        steps:
            - name: Checkout sourecode
              uses: actions/checkout@v4
              with: 
                 fetch-depth: 0
            - name: Install dependencies
              run: npm install --force
            - name: Initialize Git user
              run: | 
                  git config --global user.email "raneljohnt@gmail.com"
                  git config --global user.name "Release Workflow"
            - name: Run release
              uses: JoshuaKGoldberg/release-it-action@v0.2.2
              env: 
                GITHUB_TOKEN: ${{secrets.GH_TOKEN}}
                
            