name: Release 
on: 
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
    release:
        runs-on: ubuntu-20.04
        steps:
            - name: Checkout sourecode
              uses: actions/checkout@v4
              with: 
                 fetch-depth: 0
                 
            - name: Conventional Change Log Action
              id: changelog
              uses: TriPSs/conventional-changelog-action@v5      
              with: 
                github-token: ${{secrets.GH_TOKEN}}

            - name: Create Release
              uses: actions/create-release@v1
              if: ${{ steps.changelog.outputs.skipped == 'true' }}
              env:
                GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
              with:
                tag_name: ${{ steps.changelog.outputs.tag }}
                release_name: ${{ steps.changelog.outputs.tag }}
                body: ${{ steps.changelog.outputs.clean_changelog }}
